#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=01:00:00
#PBS -N Spike-in_sim_$EXPID
#PBS -M ${USER}@nyu.edu
#PBS -m ae
#PBS -v MYVAR="hello"
#PBS -o localhost:/scratch/${USER}/${PBS_JOBNAME}.o${EXPID}_Spike-in_sim_${PBS_JOBID}
#PBS -e localhost:/scratch/${USER}/${PBS_JOBNAME}.e${EXPID}_Spike-in_sim_${PBS_JOBID}

#------------------------------------------------------------------------------#
#                                INSTRUCTIONS                                  #
#------------------------------------------------------------------------------#
# Depends on:
    #- macs2/intel/2.1.0
    #- bedtools/intel/2.25.0

# How to run PBS script:
# Run this script as:
# $ qsub -v EXPID="task_description",DIR="path/to/dir",SAMFILE="file.sam",NREADS="number_of_reads" path/to/Fq2ReadCounts_S288C.pbs
# Example:
# $ qsub -v EXPID="Sub_1M",DIR="/scratch/lv38/Spike-in_sim/",SAMFILE="AAH119B-053013-SacCer3-2mis-PM.sam",NREADS="1e+6" ~/Pipeline/ChIP-seq_spike-in_simulations.pbs

# If you need another variable, you can change 'MYVAR' in the header
#------------------------------------------------------------------------------#

module load macs2/intel/2.1.0
module load bedtools/intel/2.25.0

echo "JobID is $PBS_JOBID"
cd $DIR

echo "SAM file subset A..."
macs2 randsample --seed 1 -f "SAM" -t $SAMFILE -n $NREADS -o A_${EXPID}_${SAMFILE}.bed --verbose 3
echo "SAM file subset B..."
macs2 randsample --seed 2 -f "SAM" -t $SAMFILE -n $NREADS -o B_${EXPID}_${SAMFILE}.bed --verbose 3

echo "Merge bedgraph files for direct comparison..."
bedtools unionbedg -i A_${EXPID}_${SAMFILE}.bed B_${EXPID}_${SAMFILE}.bed -filler NA -header > ${EXPID}_${SAMFILE}.bg

echo "
Done!
"
exit 0;
